inherit_from:
  - .rubocop_disabled.yml
  - .rubocop_enabled.yml
  - .rubocop_todo.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
